# --------------------------------------------------------------------
# Copyright (c) 2020, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

# Config map containing config.toml file for adapter

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-toml
data:
  config.toml: |
    [adapter]
    # The configuration file for mgw
    [adapter.server]
    host = "0.0.0.0"
    port = "9843"

    [[adapter.server.users]]
    username = "admin"
    password = "admin"

    [adapter.keystore]
    certPath = "/home/wso2/security/keystore/mg.pem"
    keyPath = "/home/wso2/security/keystore/mg.key"

    [adapter.truststore]
    location = "/home/wso2/security/truststore"

    [adapter.consul]
    # todo rumesh check whether we need to have certPath and KeyPath
    enable = false
    url = "https://169.254.1.1:8501" # scheme + host ip + port
    pollInterval = 5 # seconds
    aclTokenFilePath = ""
    # certs for tls
    caCertPath = "/home/wso2/security/truststore/consul/consul-agent-ca.pem"
    certPath = "/home/wso2/security/truststore/consul/local-dc-client-consul-0.pem"
    keyPath = "/home/wso2/security/truststore/consul/local-dc-client-consul-0-key.pem"

    [envoy]
    listenerHost = "0.0.0.0"
    listenerPort = 9095
    clusterTimeoutInSeconds = 20
    listenerTLSEnabled = true

    [envoy.keystore]
    certPath = "/home/wso2/security/keystore/mg.pem"
    keyPath = "/home/wso2/security/keystore/mg.key"

    [envoy.upstream]
    [envoy.upstream.tls]
    minimumProtocolVersion = "TLS1_1"
    maximumProtocolVersion = "TLS1_2"
    ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, AES128-GCM-SHA256, AES128-SHA, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-SHA, ECDHE-RSA-AES256-SHA, AES256-GCM-SHA384, AES256-SHA"
    # the default endpoint certificates
    trustedCertPath = "/etc/ssl/certs/ca-certificates.crt"
    verifyHostName = true
    disableSslVerification = false

    [enforcer]
    [enforcer.authService]
      port = 8081
      maxMessageSize = 1000000000
      maxHeaderLimit = 8192
      #keep alive time of the external authz connection
      keepAliveTime = 600
      [enforcer.authService.threadPool]
        coreSize = 400
        maxSize = 500
        #keep alive time of threads in seconds
        keepAliveTime = 600
        queueSize = 1000

    # JWT token authorization configurations. You can provide multiple JWT issuers
    # Issuer 1
    [[enforcer.jwtTokenConfig]]
        name="Resident Key Manager"
        issuer = "https://localhost:9443/oauth2/token"
        certificateAlias = "wso2carbon"
        # URL of the JWKs endpoint
        jwksURL = ""
        # Validate subscribed APIs
        validateSubscription = false
        # The claim in which the consumer key of the application is coming
        consumerKeyClaim = "azp"
        # Certificate Filepath within enforcer
        certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

    [enforcer.apimCredentials]
        username="admin"
        password="admin"

    [controlPlane]
    # Control plane's eventHub details
    [controlPlane.eventHub]
    enabled = false
    serviceUrl = "https://localhost:9443/"
    username="admin"
    password="admin"
    environmentLabels = ["Production and Sandbox"]
    retryInterval = 5
    skipSSLVerification=true
    # Message broker connection URL of the control plane
    [controlPlane.eventHub.jmsConnectionParameters]
    eventListeningEndpoints = "amqp://admin:admin@localhost:5672/"
